service: post-api-with-cicd

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  iamRoleStatements:	
  - Effect: Allow
    Action:
      - dynamodb:PutItem
    Resource: 
      - "arn:aws:dynamodb:us-east-1:651191338694:table/customerss"
functions:
  myLambdaFunction:
    handler: handler.lambda_handler
    events:
      - http: 
          path: /customerss
          method: post
  
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customerss
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
